-- ============================================
-- POSTGRESQL TYPES AND GENERATED IDENTIFIERS
-- ============================================

-- 1. SERIAL VS IDENTITY
-- SERIAL is PostgreSQL shorthand that creates an integer column, a sequence, and
-- a sequence-backed default. It is not a true standalone data type.
-- SQL-standard identity columns are the modern preferred choice for new schemas.

CREATE TEMP TABLE identity_demo (
    always_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    overrideable_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    label TEXT NOT NULL
);

INSERT INTO identity_demo (overrideable_id, label)
VALUES (100, 'caller can provide BY DEFAULT identity')
RETURNING always_id, overrideable_id, label;

-- GENERATED ALWAYS rejects an explicit value by default; OVERRIDING SYSTEM VALUE
-- is available for controlled imports. Identity generation does not imply uniqueness
-- unless a PRIMARY KEY/UNIQUE constraint is also declared.

-- 2. BOOLEAN
-- PostgreSQL BOOLEAN has TRUE, FALSE, and NULL (unknown). Accepted input spellings
-- include true/false and 1/0 in casts/input; prefer explicit TRUE/FALSE in SQL.
-- `WHERE is_active` keeps only TRUE, excluding FALSE and NULL.
-- Use `IS TRUE`, `IS FALSE`, or `IS UNKNOWN` when three-valued intent matters.

-- 3. TEXT VS VARCHAR
-- TEXT has no declared maximum length. VARCHAR(n) rejects strings longer than n
-- characters (with PostgreSQL's documented trailing-space exception on casts).
-- In PostgreSQL, TEXT and unconstrained VARCHAR have equivalent performance for
-- ordinary use; choose VARCHAR(n) only when the length limit is a real domain rule.
-- CHAR(n) is blank-padded and is rarely the right default for application strings.

-- 4. PRACTICAL TYPE EXAMPLE
CREATE TEMP TABLE type_choice_demo (
    status TEXT NOT NULL CHECK (status IN ('pending', 'complete')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. IMPORTANT RULES
-- Identity/serial sequences are not gapless; rolled-back inserts consume values.
-- A type's limit and a business invariant are different: use CHECK for value rules.
-- Prefer TIMESTAMPTZ for instants and TEXT/VARCHAR based on domain constraints.

-- 6. COMMON MISTAKES
-- Treating NULL boolean as FALSE without deciding that policy.
-- Assuming SERIAL ids are consecutive or portable to other databases.
-- Choosing VARCHAR(n) for performance when there is no genuine length requirement.

-- 7. INTERVIEW NOTES
-- Be ready to compare SERIAL/IDENTITY, explain sequence gaps, and discuss why
-- PostgreSQL TEXT is not inherently slower than VARCHAR.

-- 8. PRACTICE TASKS (no solutions)
-- Level 1: Choose types for a user's active flag, email, and creation instant.
-- Level 2: Model an imported external id alongside a generated primary key.
-- Level 3: Define whether a nullable boolean represents unknown or should be forbidden.
-- Level 4: Migrate a SERIAL primary key to IDENTITY without breaking writers or sequence state.